spring.application.name=demo

spring.datasource.name=postgres
spring.datasource.username=postgres
spring.datasource.password=No1c@nchaseme
spring.datasource.url=jdbc:postgresql://localhost:5433/College


spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:data.sql




