spring.application.name=demo

spring.datasource.name=postgres
spring.datasource.username=postgres
spring.datasource.password=No1c@nchaseme
spring.datasource.url=jdbc:postgresql://localhost:5433/College


spring.jpa.hibernate.ddl-auto=create




